# Mongo-Sync Configurations

local:
  db: 'hbk-web'
  access:
    username: 'admin'
    password: 'local_mongo_pass'
    authentication_database: 'admin'
  host:
    port: 27017

remote:
  db: 'hbk-web'
  host:
    url: '54.164.119.132'
    port: 27001
  access:
    username: 'user5MW'
    password: 'remote_mongo_pass'

# For now :local only accepts DB name and port
# Assumes DB is at localhost:port

# All of the parameters above are required,
# without them, the script will fail
